[package]
name = "log_parser"
version = "0.1.0"
edition = "2018"
description = "parse custom logs"
repository = "https://github.com/rajputrajat/log_parser.git"
license = "MIT"

[dependencies]
log = "0.4.14"
thiserror = "1.0.25"
regex = "1.5.4"
